sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

env:
 - TAGS="-tags czmq4"

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - libsodium-dev
    - libczmq-dev

script:
 - go get -d -t -v $TAGS ./...
 - go install -v $TAGS ./...
 - go test -v $TAGS ./...
 - go test -v $TAGS -race ./...

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: always
    on_failure: always

